spring:
  profiles: qa
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # connection pool
      filters: stat
      initial-size: 10
      min-idle: 10
      max-active: 300
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      #      max-evictable-idle-time-millis:
      time-between-eviction-runs-millis: 60000
      #      validation-query: 'SELECT 1'
      #      validation-query-timeout: 1000
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # memory leak
      async-init: false
      keep-alive: true
      remove-abandoned: false
      remove-abandoned-timeout-millis: 180
      log-abandoned: false
      moniter:
        stat-view-servlet:
          enabled: true
          login-username: admin
          login-password: 'admin123!'
          url-pattern: /druid/*
          reset-enable: true
        web-stat-filter:
          enabled: true
          url-pattern: /api/*
          profile-enable: true
          session-stat-enable: true
        filter:
          stat:
            enabled: true
            db-type: mysql
            log-slow-sql: true
            slow-sql-millis: 2000
server:
  port: 8088
  servlet:
    context-path: /

logging:
  level:
    ROOT: TRACE
    com.niyongcheng.jettydemo: TRACE

mybatis:
  type-aliases-package: com.niyongcheng.jettydemo.entity
  mapper-locations: classpath:dao/*Mapper.xml

